# Generated by Django 6.0.1 on 2026-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expires_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
