from rest_framework import serializers
from api.models import Image

class ImageSerializer(serializers.ModelSerializer):
    # file_path is read_only: generated by backend
    file_path = serializers.CharField(read_only=True)

    class Meta:
        model = Image
        fields = ["id", "file_path", "original_filename", "is_primary", "uploaded_at"]
        read_only_fields = ["id", "file_path", "uploaded_at"]
